### ISSUE TITLE
最后一个大代码段($$)后的内容全部消失

### ISSUE THREAD

**Issue by PkuCuipy** [marsggbo/zhihu_markdown_converter#2]
如果最后一个大代码段后面还有内容, 
这些内容不会出现在新生成的markdown文件中

**Comment by PkuCuipy** [comment]
似乎见到了解决, 在 parse_data() return语句前加上 "new_data_str += data_str[prev_index:]"即可

**Comment by marsggbo** [comment]
你好，你能提交一下你的版本代码吗？谢谢
